### ISSUE TITLE
字典传引用污染header

### ISSUE THREAD

**Issue by Mai-icy** [Dimlitter/QCZJ-Auotstudy#5]
在`main.py`内第54,55行
```       
tempheaders = self.headers
tempheaders.update(headers)
```
tempheaders将修改self.headers，污染原来的header
是否应修改为
`tempheaders = self.headers.copy()`
（虽然不影响运行结果，但是细节还是很想说）

**Comment by Dimlitter** [comment]
@Mai-icy 改，都可以改！

**Comment by Dimlitter** [comment]
已在 [@17edeca](https://github.com/Dimlitter/QCZJ-Autostudy/commit/17edecac77c25cd4946917f94fc97dff3df958d5) 中解决，感谢您的反馈！（说实话您为啥不来个PR呢：）
