### ISSUE TITLE
无法抓包

### ISSUE THREAD

**Issue by Mai-icy** [Dimlitter/QCZJ-Auotstudy#6]
在尝试抓包时貌似有SSL-pinning，一旦开启抓包代理就无法接受网站数据

**Comment by Mai-icy** [comment]
发现其原理为在打开“大学习”的时候会有一个中转网址，内部包含了许多参数，包括openid等，并且中转网址可以在浏览器打开进行抓包（浏览器自动配置证书）

**Comment by Dimlitter** [comment]
感谢反馈！
